import bcrypt from 'bcryptjs';
export const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Sapiens',
      genre: ['history', 'non-fiction', 'philosophy'],
      image: '/images/sapiens.jpg',
      slug: 'sapiens',
      author: 'Yuval Noah Harari',
      price: 70,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Six of Crows',
      genre: ['fiction', 'fantasy'],
      image: '/images/six-of-crows.jpg',
      slug: 'six-of-crows',
      author: 'George R.R Martin',
      price: 80,
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Deep Work',
      genre: ['non-fiction', 'self-help'],
      slug: 'deep-work',
      image: '/images/deep-work.jpg',
      author: 'Cal Newport',
      price: 90,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: '1984',
      genre: ['classics', 'fiction'],
      image: '/images/1984.jpg',
      slug: '1984-orwell',
      author: 'George Orwell',
      price: 90,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'The Three-Body Problem',
      genre: ['science-fiction', 'fiction'],
      image: '/images/three-body-problem.jpg',
      slug: 'three-body-problem',
      author: 'Cixin Liu',
      price: 95,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Crime and Punishment',
      genre: ['classics', 'fiction', 'philosophy'],
      image: '/images/crime-punishment.jpg',
      slug: 'crime-punishment',
      author: 'Fyodor Dostoevsky',
      price: 75,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};
